SELECT * FROM EMPREGADO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM CLIENTE;
/*LIKE*/

/*Exibir todos os empregados cujo sobrenome comece com a letra N*/
-- % ==> QUAISQUER NUMERO DE CARACTERES (INCLUSIVE NENHUM)
-- _ ==> qUALQUER CARACTERER (APENAS UM)

SELECT * FROM EMPREGADO WHERE ULT_NOME LIKE 'N%';

/*Exibir todos os empregados cujo sobrenome comece com letra Ne*/
SELECT * FROM EMPREGADO WHERE ULT_NOME LIKE 'Ne%';

/*Exibir todos os empregados cujo sobrenome termine com a letra S*/
SELECT * FROM EMPREGADO WHERE ULT_NOME LIKE '%s';

/*Exibir todos os empregados cujo nome tenha a letra U*/
SELECT * FROM EMPREGADO WHERE PRIM_NOME LIKE '%u%';

/*Exibir todos os empregados cujo nome tenha a letra M*/
SELECT * FROM EMPREGADO WHERE PRIM_NOME LIKE '%M%';
SELECT * FROM EMPREGADO WHERE PRIM_NOME LIKE '%m%';
SELECT * FROM EMPREGADO WHERE UPPER(PRIM_NOME) LIKE '%M%';
SELECT * FROM EMPREGADO WHERE LOWER(PRIM_NOME) LIKE '%m%';

SELECT * FROM EMPREGADO WHERE UPPER(PRIM_NOME) LIKE 'M%' AND SALARIO > 10000;

/*Exibir todos os empregados cujo sobrenome tenha a letra O como segunda letra*/

SELECT * FROM EMPREGADO WHERE ULT_NOME LIKE '_o%';

SELECT * FROM EMPREGADO WHERE PRIM_NOME LIKE '_____';

/*NULL*/
/*Exibir todos os empregados que NAO tenham gerentes*/
SELECT * FROM EMPREGADO WHERE ID_GERENTE IS NULL;

/*Exibir todos os empregados que tenham gerentes*/
SELECT * FROM EMPREGADO WHERE ID_GERENTE IS NOT NULL;

/*Juncoes*/
SELECT * FROM EMPREGADO;
SELECT * FROM DEPARTAMENTO;

/*Juncao Crusadas*/
SELECT * FROM EMPREGADO CROSS JOIN DEPARTAMENTO;

/*Juncao Interior*/

/*IDENTIFICANDO AS COLUNAS AMBIGUAS*/

SELECT * FROM EMPREGADO INNER JOIN DEPARTAMENTO 
ON EMPREGADO.ID_DEPTO = DEPARTAMENTO.ID;

SELECT * FROM EMPREGADO EMP INNER JOIN DEPARTAMENTO DEP
ON EMP.ID_DEPTO = DEP.ID;

SELECT * FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID;

/*ID EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO*/

SELECT E.ID, E.ULT_NOME, E.PRIM_NOME, E.SALARIO, D.NOME
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID;

/*ID EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO EMPREGADO COM SALARIO > 7500*/

SELECT E.ID, E.ULT_NOME, E.PRIM_NOME, E.SALARIO, D.NOME
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE E.SALARIO > 7500;

/*ID EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO EMPREGADO QUE TRABALHAM EM VENDAS*/

SELECT E.ID, E.ULT_NOME, E.PRIM_NOME, E.SALARIO, D.NOME
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE UPPER(D.NOME) = 'VENDAS';

/*Juncao Exterior*/

SELECT E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", C.NOME AS "CLIENTE"
FROM EMPREGADO E INNER JOIN CLIENTE C
ON E.ID = C.VENDEDOR;

SELECT E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", C.NOME AS "CLIENTE"
FROM EMPREGADO E RIGHT JOIN CLIENTE C
ON E.ID = C.VENDEDOR;

SELECT E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", C.NOME AS "CLIENTE"
FROM EMPREGADO E LEFT JOIN CLIENTE C
ON E.ID = C.VENDEDOR;

SELECT E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", C.NOME AS "CLIENTE"
FROM CLIENTE C RIGHT JOIN EMPREGADO E
ON E.ID = C.VENDEDOR;

/*CLIENTE QUE NAO E ATENDIDO POR NENHUM VENDEDOR*/

SELECT E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", C.NOME AS "CLIENTE"
FROM EMPREGADO E RIGHT JOIN CLIENTE C
ON E.ID = C.VENDEDOR
WHERE E.ULT_NOME IS NULL;

/***FUNCOES DE GRUPO***/

/*LISTAR O SALARIO MEDIO E A SOMA DOS SALARIOS*/
SELECT * FROM EMPREGADO;

SELECT AVG(SALARIO) FROM EMPREGADO; -- MEDIA
SELECT SUM(SALARIO) FROM EMPREGADO; -- SOMA
SELECT MAX(SALARIO) FROM EMPREGADO; -- MAIOR VALOR
SELECT MIN(SALARIO) FROM EMPREGADO; -- MENOR VALOR
SELECT COUNT(SALARIO) FROM EMPREGADO; -- CONTA QUANTOS REGISTROS POSSUEM VALOR

SELECT MAX(PRIM_NOME) FROM EMPREGADO;
SELECT MIN(PRIM_NOME) FROM EMPREGADO;

SELECT MAX(DT_ADMISSAO) FROM EMPREGADO;
SELECT MIN(DT_ADMISSAO) FROM EMPREGADO;

SELECT COUNT(ID_GERENTE) FROM EMPREGADO;

SELECT ID_DEPTO, AVG(SALARIO) FROM EMPREGADO GROUP BY ID_DEPTO;

/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS
 * DOS EMPREGADOS DE CADA DEPARTAMENTO*/
 
 SELECT ID_DEPTO, COUNT(ID), AVG(SALARIO), SUM (SALARIO) FROM EMPREGADO GROUP BY ID_DEPTO;
 
/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS DOS 
* EMPREGADOS DE CADA  DEPARTAMENTO E DENTRO DO DEPARTAMENTO PARA
* CADA CARGO 
*/

SELECT ID_DEPTO, CARGO, COUNT(ID), AVG(SALARIO), SUM(SALARIO)
FROM EMPREGADO 
GROUP BY ID_DEPTO, CARGO;


SELECT ID_DEPTO, CARGO, COUNT(ID), AVG(SALARIO), SUM(SALARIO)
FROM EMPREGADO 
WHERE ID_DEPTO IN (10, 20)
GROUP BY ID_DEPTO, CARGO;

SELECT ID_DEPTO, CARGO, COUNT(ID), AVG(SALARIO), SUM(SALARIO)
FROM EMPREGADO 
WHERE ID_DEPTO IN (10, 20)
GROUP BY ID_DEPTO, CARGO
HAVING COUNT(ID) = 1;

SELECT ID_DEPTO, CARGO, COUNT(ID), AVG(SALARIO), SUM(SALARIO)
FROM EMPREGADO 
WHERE ID_DEPTO IN (10, 20)
GROUP BY ID_DEPTO, CARGO
HAVING COUNT(ID) = 1
ORDER BY AVG(SALARIO);


SELECT * FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE UPPER(D.NOME) = 'VENDAS';

/*Subqueries*/
/*Empregados do departamento de vendas*/

SELECT ID FROM DEPARTAMENTO WHERE UPPER(NOME) = 'VENDAS';

SELECT * FROM EMPREGADO
WHERE ID_DEPTO = (SELECT ID FROM DEPARTAMENTO WHERE UPPER(NOME) = 'VENDAS');

SELECT * FROM EMPREGADO
WHERE ID_DEPTO = 20;

/*Empregados que ganham mais que o salario medio da empresa*/

SELECT * FROM EMPREGADO
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPREGADO);

/*Empregados que ganham salario maiores que todos os vendedores*/

SELECT * FROM EMPREGADO
WHERE SALARIO > ALL (SELECT SALARIO FROM EMPREGADO WHERE UPPER(CARGO) = 'VENDEDOR');

/*Empregados que ganham salarios maiores que algum vendedor*/
SELECT * FROM EMPREGADO
WHERE SALARIO > ANY (SELECT SALARIO FROM EMPREGADO WHERE UPPER(CARGO) = 'VENDEDOR');