-- EXECUTAR O SCRIPT criacao_agencia_Seguros.sql PARA A CRIAÇÃO E CARGA DAS TABELAS.

-- EXECUTAR AS CONSULTAS ABAIXO

-- EXIBIR TODAS AS LINHAS E TODAS AS COLUNAS DA TABELA VEICULO


-- EXIBIR TODAS AS LINHAS E TODAS AS COLUNAS DA TABELA MODELO


-- EXIBIR TODAS AS LINHAS E TODAS AS COLUNAS DA TABELA PROPRIETARIO


-- EXIBIR A COR E A PLACA DE TODOS OS VEICULOS


-- EXIBIR O NOME E O CPF DE TODOS OS PROPRIETARIOS


-- EXIBIR O NOME DE TODOS OS MODELOS


-- EXIBIR AS CORES UNICAS DOS VEICULOS 


-- EXIBIR TODOS OS DADOS DO VEICULO DE PLACA LGA4674


-- EXIBIR TODOS OS DADOS DOS VEICULOS DE MODELO 101


-- EXIBIR A PLACA, A COR E O MODELO DE TODOS OS VEICULOS FABRICADOS EM 2010


-- EXIBIR TODAS AS INFORMAÇÕES DOS VEICULOS QUE POSSUAM UM VALOR DE SEGURO SUPERIOR A 35000


-- EXIBIR O CPF DE DILMA NEVES


-- EXIBIR O CODIGO DO PROPRIETARIO, A COR E O VALOR DO SEGURO DE TODOS OS VEICULOS DE COR PRETA E QUE FORAM FABRICADOS EM 2009 


-- EXIBIR O CODIGO DO PROPRIETARIO, A PLACA E O VALOR DO SEGURO DE TODOS OS VEICULOS DE COR VERMELHA OU QUE FORAM FABRICADOS ANTES DE 2013 


-- EXIBIR O CODIGO DO PROPRIETARIO, A PLACA E A COR DE TODOS OS VEICULOS DE COR VERDE OU AMARELA


-- EXIBIR O CODIGO DO PROPRIETARIO, A COR E A PLACA DE TODOS OS VEICULOS QUE NÃO POSSUEM A COR PRETA OU BRANCA


-- EXIBIR TODOS OS DADOS DOS VEICULOS QUE POSSUAM UM VALOR DE SEGURO ENTRE 15000 E 35000


-- EXIBIR TODOS OS DADOS DOS VEICULOS QUE NÃO FORAM FABRICADOS ENTRE 2010 E 2014


-- EXIBIR TODOS OS DADOS DOS PROPRIETARIOS CUJO NOME COMECE COM A LETRA M


-- EXIBIR TODOS OS DADOS DOS PROPRIETARIOS CUJO NOME TERMINECOM A LETRA S


-- EXIBIR TODOS OS DADOS DOS PROPRIETARIOS CUJO NOME POSSUA DUAS LETRAS L SEGUIDAS


-- EXIBIR TODOS OS DADOS DOS PROPRIETARIOS CUJO A SEGUNDA LETRA DO NOME SEJA A


-- EXIBIR TODOS OS DADOS DOS VEICULOS QUE POSSUAM VALOR DE SEGURO CALCULADO


-- EXIBIR TODOS OS DADOS DOS VEICULOS QUE NÃO POSSUAM VALOR DE SEGURO CALCULADO